### ISSUE TITLE
No highlighting in neovim

### ISSUE THREAD

**Issue by teonnik** [ColinKennedy/tree-sitter-usd#6]
There is no syntax highlighting when the library is installed and configured in neovim:

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/8088032/b0046d6f-72a6-42b4-913b-d829fa9a40a4)

TSConfigInfo:

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/8088032/c8f6f62a-00b2-40ac-b4de-bf13cd62c279)

**Architecture**

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/8088032/c18e2782-e214-4f25-b71f-d0800a2f545c)

Neovim (with bundled treesitteer) version:

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/8088032/a326cde0-6d97-48be-9682-80582d08a86f)

My theme is [gruvbox](https://github.com/ellisonleao/gruvbox.nvim)

**Comment by ColinKennedy** [comment]
When you move your cursor over a keyword and do `:Inspect` what's the output? And what's the output of `:InspectTree`? It's possible that the grammar is fine but your configuration doesn't have `set syntax` enabled or something.

This is what my `:InspectTree` looks like

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/10103049/5600dc47-a42e-4d84-ae8a-37e412b2611d)

If `:InspectTree` is empty, try calling `:lua vim.treesitter.start(0, "usd")` on the current buffer and try `:InspectTree` again.

**Comment by teonnik** [comment]
Calling `:lua vim.treesitter.start(0, "usd")`  seems to make things work:

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/8088032/0d184cf1-6292-4e01-b965-43b843496e6c)

`:InspectTree` fails regardless of whether it's called before or after the `start()` call:

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/8088032/34c384db-67d0-42cf-a7ae-67a77be5f054)

`:Inspect` works after the `start()` call:

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/8088032/534677cb-976a-4315-86be-8b0683ec6a1a)

but not before : 

![image](https://github.com/ColinKennedy/tree-sitter-usd/assets/8088032/284257e9-8562-4b77-9708-91f26c4b9dad)

`set syntax` returns : `syntax=conf`

**Comment by ColinKennedy** [comment]
If I remember right, the `:InspectTree` loads using your `filetype` attribute. And filetype is detected by the name of the file extension

e.g. `main.usda`, on open
`set filetype?` = `usd`
`set syntax?` = ``

If yours prints back

`set filetype?` = `conf or something else or ""`
`set syntax?` = `conf`

Then that would explain all that we've seen so far. e.g. highlighting works but only after calling `lua vim.treesitter.start(0, "usd")` but `:InspectTree` still fails because it's reading from your `set filetype?` which is incorrectly set. Filetype discovery is controlled by https://github.com/vim/vim/blob/ea999037a41292b3d3e00700a87a82fe5d2c12b2/runtime/filetype.vim#L3033-L3034. And it works for .usd and .usda extensions.

What's the name of the file that you're trying to load? Can you confirm that `set filetype?` = `usd` on start-up?

**Comment by teonnik** [comment]
Indeed, as you suggested, there appears to be a problem with `filetype`: `set filetype?` = `conf`. If I set it to `usd`, highlighting works and `:InspectTree` works. 

I now wonder why files with `.usda` and `.usd` extensions are not recognized as `filetype = usd` in my setup? I have nothing unusual happening with `filetype` in my config. In fact, the only lines in my config with `filetype` are:

```vim
filetype indent on  " load filetype-specific indent files
filetype plugin on  " enable filetype plugins
au BufEnter *.tpp :setlocal filetype=cpp
```

**Comment by ColinKennedy** [comment]
Looking at your Neovim version again, 0.9.5, isn't that version out of date?

0.9.5 is this release - https://github.com/neovim/neovim/commit/8744ee8783a8597f9fce4a573ae05aca2f412120. And the equivalent path in Neovim is `{neovim_root}/runtime/lua/vim/filetype.lua`. https://github.com/neovim/neovim/blob/8744ee8783a8597f9fce4a573ae05aca2f412120/runtime/lua/vim/filetype.lua doesn't have usd filetypes yet. But it does exist in master.

Once Neovim 0.10 you can upgrade to that. In the meantime there's the option to compile from source.

Let me know if compiling Neovim from master / nightly solves it and, if so, I can update the README.md to specify Neovim 0.10+ as a requirement if you intend to use this grammar for that editor.

**Comment by teonnik** [comment]
> 0.9.5 is this release - https://github.com/neovim/neovim/commit/8744ee8783a8597f9fce4a573ae05aca2f412120. And the equivalent path in Neovim is {neovim_root}/runtime/lua/vim/filetype.lua. https://github.com/neovim/neovim/blob/8744ee8783a8597f9fce4a573ae05aca2f412120/runtime/lua/vim/filetype.lua doesn't have usd filetypes yet. But [it does exist in master](https://github.com/neovim/neovim/blob/af8500af64571f787579b60bf0064cd05655fd51/runtime/lua/vim/filetype.lua#L1100).

Good catch, that is indeed the issue. Neovim 0.10 will be released in 1 week. I can test once it's out. The workaround works for now: `au BufNewFile,BufRead *.usda,*.usd		setf usd`. Thanks for the help. :)
